version: 2.1

orbs:
  shellcheck: circleci/shellcheck@1.3.15

workflows:
  commit:
    jobs:
      - shellcheck/check:
          path: src/
      - test
  nightly:
    triggers:
      - schedule:
          cron: 0 0 * * *
          filters:
            branches:
              only:
                - master
    jobs:
      - shellcheck/check:
          path: src/
      - test

jobs:
  test:
    docker:
      - image: particleflux/circleci-bats-kcov:1.1.0

    steps:
      - checkout

      # install codeclimate test reporter
      - restore_cache:
          keys:
            - v3-dependencies

      - run:
          name: Install test dependencies
          command: |
            if [[ ! -f "/tmp/cc-test-reporter" ]]; then
              curl -sSL -o /tmp/cc-test-reporter \
                https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64
            fi
            chmod +x /tmp/cc-test-reporter

            shellmock_version=1.0
            curl -sSL "https://github.com/capitalone/bash_shell_mock/archive/$shellmock_version.tar.gz" | tar xvz -C /tmp
            cd "/tmp/bash_shell_mock-$shellmock_version/"
            ./install.sh $HOME

      - save_cache:
          paths:
            - /tmp/cc-test-reporter
          key: v3-dependencies

      - run:
          command: |
            export PATH="$HOME/bin:$PATH"

            # a normal test run before the coverage one; it has better output
            bats tests/

            /tmp/cc-test-reporter before-build
            kcov --include-path=. --exclude-path=tests coverage bats tests/ &> /dev/null
            xml="$(ls -1 coverage/bats*/cobertura.xml | head -1)"

            # removing trailing slash in cobertura <source>
            # this works around an issue with the codeclimate formatter
            sed -ri "s#<source>(.+)/</source>#<source>\1</source>#" "$xml"

            /tmp/cc-test-reporter format-coverage $xml --input-type cobertura
            /tmp/cc-test-reporter upload-coverage

      - store_artifacts:
          path: coverage
